keymap:
  - name: terminal copy 
    application:
      only: Alacritty 
    remap:
      Alt_L-c: C-Shift-c
      Alt_L-v: C-Shift-v

modmap:
  - name: Global
    application:
      not: [Alacritty, steam, dota2, qemu-system-x86_64, qemu, Qemu-system-x86_64]
    remap:
      Alt_L: Ctrl_L 
