set -g status-style "bg=#1E1E2E,fg=#CDD6F4"
set -g status-left-style "bg=#1E1E2E,fg=#CDD6F4"
set -g status-right-style "bg=#1E1E2E,fg=#A6ADC8"
set -g window-status-style "bg=#1E1E2E,fg=#A6ADC8"
set -g window-status-current-style "bg=#89B4FA,fg=#1E1E2E,bold"
set -g pane-border-style "fg=#313244"
set -g pane-active-border-style "fg=#89B4FA"
set -g message-style "bg=#89B4FA,fg=#1E1E2E"
set -g mode-style "bg=#313244,fg=#CDD6F4"
