set -g status-style "bg=#fffbef,fg=#5c6a72"
set -g status-left-style "bg=#fffbef,fg=#3a515d"
set -g status-right-style "bg=#fffbef,fg=#708089"
set -g window-status-style "bg=#fffbef,fg=#708089"
set -g window-status-current-style "bg=#8da101,fg=#fffbef,bold"
set -g pane-border-style "fg=#d8caac"
set -g pane-active-border-style "fg=#8da101"
set -g message-style "bg=#35a77c,fg=#fffbef"
set -g mode-style "bg=#edeada,fg=#3a515d"
