set -g status-style "bg=#272E33,fg=#D3C6AA"
set -g status-left-style "bg=#272E33,fg=#D3C6AA"
set -g status-right-style "bg=#272E33,fg=#859289"
set -g window-status-style "bg=#272E33,fg=#859289"
set -g window-status-current-style "bg=#A7C080,fg=#272E33,bold"
set -g pane-border-style "fg=#4F5B58"
set -g pane-active-border-style "fg=#A7C080"
set -g message-style "bg=#7FBBB3,fg=#272E33"
set -g mode-style "bg=#3C4841,fg=#D3C6AA"
