set -g status-style "bg=#FFFBEF,fg=#5C6A72"
set -g status-left-style "bg=#FFFBEF,fg=#3A515D"
set -g status-right-style "bg=#FFFBEF,fg=#708089"
set -g window-status-style "bg=#FFFBEF,fg=#708089"
set -g window-status-current-style "bg=#8DA101,fg=#FFFBEF,bold"
set -g pane-border-style "fg=#D8CAAC"
set -g pane-active-border-style "fg=#8DA101"
set -g message-style "bg=#35A77C,fg=#FFFBEF"
set -g mode-style "bg=#EDEADA,fg=#3A515D"
