set -g status-style "bg=default,fg=#575279"
set -g status-left-style "bg=default,fg=#575279"
set -g status-right-style "bg=default,fg=#797593"
set -g window-status-style "bg=default,fg=#797593"
set -g window-status-current-style "bg=#d7827e,fg=#faf4ed,bold"
set -g pane-border-style "fg=#dfdad9"
set -g pane-active-border-style "fg=#d7827e"
set -g message-style "bg=#d7827e,fg=#faf4ed"
set -g mode-style "bg=#f2e9e1,fg=#575279"
