set -g status-style "bg=#faf4ed,fg=#575279"
set -g status-left-style "bg=#faf4ed,fg=#575279"
set -g status-right-style "bg=#faf4ed,fg=#797593"
set -g window-status-style "bg=#faf4ed,fg=#797593"
set -g window-status-current-style "bg=#b4637a,fg=#faf4ed,bold"
set -g pane-border-style "fg=#dfdad9"
set -g pane-active-border-style "fg=#b4637a"
set -g message-style "bg=#b4637a,fg=#faf4ed"
set -g mode-style "bg=#f2e9e1,fg=#575279"
