# This file is auto-generated by scripts/update-vscode-extensions.py
# Do not edit manually; run the script after changing vscode-extensions.txt.
{ pkgs }:
let
  inherit (pkgs.vscode-utils) buildVscodeMarketplaceExtension;
in [

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "activitywatch";
    name = "aw-watcher-vscode";
    version = "0.5.0";
    hash = "sha256-OrdIhgNXpEbLXYVJAx/jpt2c6Qa5jf8FNxqrbu5FfFs="; # engine ^1.23.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "arcticicestudio";
    name = "nord-visual-studio-code";
    version = "0.19.0";
    hash = "sha256-awbqFv6YuYI0tzM/QbHRTUl4B2vNUdy52F4nPmv+dRU="; # engine ^1.12.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "bazelbuild";
    name = "vscode-bazel";
    version = "0.12.0";
    hash = "sha256-H0MAoqEQcT/tuDbiubCf9DCHt55M5Nx6IxzU5a3l5bo="; # engine ^1.88.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "catppuccin";
    name = "catppuccin-vsc";
    version = "3.18.0";
    hash = "sha256-57c0HRdEABLz03qozeQgFJH1NaWUbA+7tDJv0V4At8M="; # engine ^1.80.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "charliermarsh";
    name = "ruff";
    version = "2025.26.0";
    hash = "sha256-EL07b5q4EvTApuUeBK+W+ydOd0Wid9hLaOK2XAw9xhg="; # engine ^1.75.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "cunbidun";
    name = "flash-vscode";
    version = "0.0.9";
    hash = "sha256-hZ1QPSOvlaG9SyQ2NWbe9Xv1l6UdVqYmt7ifJE8yxtg="; # engine ^1.96.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "foxundermoon";
    name = "shell-format";
    version = "7.2.8";
    hash = "sha256-Z3vmRzqPCxkQbn39I54bh/ND+0HcE9iFUhKQ29GRd7o="; # engine ^1.36.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "github";
    name = "copilot";
    version = "1.376.1794";
    hash = "sha256-PZIxhDFFTARM25LDjg+Y3n0+oHMDKkvWjh4QNxy6CHc="; # engine ^1.103.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "james-yu";
    name = "latex-workshop";
    version = "10.10.2";
    hash = "sha256-Ls02bUSh5O5mDT2SEnaibvpHw535yelv5NaQ/NRM13k="; # engine ^1.96.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "kamadorueda";
    name = "alejandra";
    version = "1.0.0";
    hash = "sha256-COlEjKhm8tK5XfOjrpVUDQ7x3JaOLiYoZ4MdwTL8ktk="; # engine ^1.64.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-python";
    name = "black-formatter";
    version = "2025.3.11831009";
    hash = "sha256-FsJHxYHae1NuDXQfOJ4TPnXDy05tTuyCElHD4MiaMDU="; # engine ^1.82.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-python";
    name = "debugpy";
    version = "2025.15.2025100201";
    hash = "sha256-FvZb8caR2S3vgulcbFtCANs4SM3Ia5MXs8dFNndBMKs="; # engine ^1.92.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-python";
    name = "isort";
    version = "2025.1.12731007";
    hash = "sha256-/eAN5oc4y4KTzvjGoU0Kx0u4nUxmndldoMqzPv4K2fM="; # engine ^1.74.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-python";
    name = "python";
    version = "2025.17.2025100201";
    hash = "sha256-du0XHHtARbmnYb7MdMJMfuPcXKhEEg3xLZ6nberNz7U="; # engine ^1.95.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-python";
    name = "vscode-pylance";
    version = "2025.8.3";
    hash = "sha256-+IyB1tCBWjKZzN9yydOiyv3SUIKqfkbGTOsbjoDjlKo="; # engine ^1.101.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-python";
    name = "vscode-python-envs";
    version = "1.11.12751011";
    hash = "sha256-w8vg4DY1UqKPq2344Q81/X+5HMa95Cby2jrTTE56fW4="; # engine ^1.104.0-20250815
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-toolsai";
    name = "datawrangler";
    version = "1.23.0";
    hash = "sha256-bu0uxVem36CbrSmYlVTcostHcLWpMFt4NxJJSsADxVk="; # engine ^1.82.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-toolsai";
    name = "jupyter";
    version = "2023.10.1003011100";
    hash = "sha256-/fgCIqxrzNL7XRrPOPW7kpvx2nRmjpMF+o7ZhDRtnwE="; # engine ^1.83.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-toolsai";
    name = "jupyter-keymap";
    version = "1.1.2";
    hash = "sha256-9BLyBZzZ0Z6QQ05QSxFJYNZmZDc5O3eYkCxe/UsmKws="; # engine ^1.79.0-insider
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-toolsai";
    name = "jupyter-renderers";
    version = "1.3.2025062701";
    hash = "sha256-z6XjcI1mh3/Ot82NJQEVBsFBOPkU7vxUuV1McApi3gw="; # engine ^1.95.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-toolsai";
    name = "vscode-jupyter-cell-tags";
    version = "0.1.9";
    hash = "sha256-XODbFbOr2kBTzFc0JtjiDUcCDBX1Hd4uajlil7mhqPY="; # engine ^1.88.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-toolsai";
    name = "vscode-jupyter-slideshow";
    version = "0.1.6";
    hash = "sha256-fnsMrrcYdz6BzUWMd9pAOQGTjmtEbQeoVYG20VWxCsM="; # engine ^1.88.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-vscode-remote";
    name = "remote-ssh";
    version = "0.121.2025093015";
    hash = "sha256-CQJIDtNFFPo9JsXk4neAKUYQ8mc/Aw+gBXECU8lkcOs="; # engine ^1.96.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-vscode-remote";
    name = "remote-ssh-edit";
    version = "0.87.0";
    hash = "sha256-yeX6RAJl07d+SuYyGQFLZNcUzVKAsmPFyTKEn+y3GuM="; # engine ^1.74.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-vscode";
    name = "cpptools";
    version = "1.28.0";
    hash = "sha256-g/wunZGVM4l6n4Tr9xqjT27BdWgY3tbU6y4YB1CJmno="; # engine ^1.67.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "ms-vscode";
    name = "remote-explorer";
    version = "0.6.2025081809";
    hash = "sha256-u6OIRbNjE5B2qlm8x2gU+zSudBf6yPI4gxWB6Qu1OoM="; # engine ^1.87.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "pkief";
    name = "material-icon-theme";
    version = "5.27.0";
    hash = "sha256-vP5jMijMIKHUmvSaTX+eEO6Z3dzUCR6S/ZdPxjJHIT8="; # engine ^1.55.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "streetsidesoftware";
    name = "code-spell-checker";
    version = "4.2.6";
    hash = "sha256-veP2G/5vcaimjd98ur6Mhl4x1NKuvS21oO+HFJLHN+I="; # engine ^1.90.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "tamasfe";
    name = "even-better-toml";
    version = "0.21.2";
    hash = "sha256-IbjWavQoXu4x4hpEkvkhqzbf/NhZpn8RFdKTAnRlCAg="; # engine ^1.90.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "timonwong";
    name = "shellcheck";
    version = "0.38.3";
    hash = "sha256-qDispRN7jRIIsP+5lamyR+sNoOwTwl+55QftzO7WBm4="; # engine ^1.66.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "vscodevim";
    name = "vim";
    version = "1.30.1";
    hash = "sha256-cKdVQTGj7R37YefQAaTspF1RVul/9wv7u9b5TpGZN5k="; # engine ^1.74.0
  };
})

(buildVscodeMarketplaceExtension {
  mktplcRef = {
    publisher = "zhuangtongfa";
    name = "material-theme";
    version = "3.19.0";
    hash = "sha256-K0eXeAEn4s3YZHJJU9jxtytNQTgaGwvd3fBUsZiKfPw="; # engine ^1.76.0
  };
})
]
