#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 
 
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

#boder color
bspc config focused_border_color "#88C0D0"
bspc config normal_border_color "#e6eef3"
bspc config active_border_color "#eceff4"
bspc config presel_feedback_color "#A3BE8C"

# rule for starting windows
bspc rule -a Chromium desktop='^3'
bspc rule -a Slack desktop='^9'

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# launch programs
xset r rate 200 30 &
feh --bg-fill --randomize ~/.wallpapers/nord/* &
picom --experimental-backends &
nm-applet &
~/.config/polybar/launch.sh &
dunst &
ibus-daemon -drx &
