#!/bin/sh

systemctl --user import-environment PATH XDG_DATA_DIRS HOME TERMINAL PICKER EDITOR
systemctl --user import-environment GLFW_IM_MODULE GTK_IM_MODULE QT_IM_MODULE XMODIFIERS NIX_PROFILES # for keyboard
systemctl --user start hyprland.service
