[pyprland]
plugins = [
  "scratchpads",
  "toggle_special",
]

[scratchpads.term]
command = "alacritty -t __scratchpad"
animation = ""
lazy = true
unfocus = ""
size = "50% 50%"
position = "25% 25%"
excludes = "*"

[scratchpads.messenger]
command = "caprine"
animation = ""
unfocus = ""
lazy = true
size = "50% 50%"
position = "25% 25%"
excludes = "*"
class = "Caprine"
match_by =  "class"

[scratchpads.spotify]
command = "spotify"
animation = ""
unfocus = ""
lazy = true
size = "50% 50%"
position = "25% 25%"
excludes = "*"

[scratchpads.signal]
command = "signal-desktop"
animation = ""
unfocus = ""
lazy = true
size = "50% 50%"
position = "25% 25%"
excludes = "*"

[scratchpads.obsidian]
command = "obsidian"
animation = ""
unfocus = ""
lazy = true
size = "75% 75%"
position = "12% 12%"
excludes = "*"