# vim:ft=kitty

## name: Theme Manager Default Dark
## author: cunbidun

foreground #F5F5F7
background #1C1C1E
background_opacity 0.75
selection_foreground #FFFFFF
selection_background #0A84FF

cursor #0A84FF
cursor_text_color #FFFFFF

url_color #0A84FF

active_tab_foreground #FFFFFF
active_tab_background #0A84FF
inactive_tab_foreground #AEAEB2
inactive_tab_background #2C2C2E
tab_bar_background #1C1C1E

color0 #1C1C1E
color8 #3A3A3C

color1 #FF453A
color9 #FF6961

color2 #32D74B
color10 #34C759

color3 #FFD60A
color11 #FFE066

color4 #0A84FF
color12 #5AC8FA

color5 #BF5AF2
color13 #DA8FFF

color6 #64D2FF
color14 #5AC8FA

color7 #D1D1D6
color15 #F5F5F7
