# vim:ft=kitty

## name: Theme Manager Default Light
## author: cunbidun

foreground #1D1D1F
background #F5F5F7
background_opacity 0.92
selection_foreground #FFFFFF
selection_background #007AFF

cursor #007AFF
cursor_text_color #FFFFFF

url_color #007AFF

active_tab_foreground #FFFFFF
active_tab_background #007AFF
inactive_tab_foreground #6E6E73
inactive_tab_background #FFFFFF
tab_bar_background #F5F5F7

color0 #1D1D1F
color8 #6E6E73

color1 #FF3B30
color9 #FF6961

color2 #28CD41
color10 #30D158

color3 #FFCC00
color11 #FFD60A

color4 #007AFF
color12 #0A84FF

color5 #AF52DE
color13 #BF5AF2

color6 #32ADE6
color14 #64D2FF

color7 #6E6E73
color15 #1D1D1F
