MY_EDITOR='nvim'
export EDITOR=$MY_EDITOR
export VISUAL=$MY_EDITOR

export LANG=en_US.UTF-8
export TERM="xterm-256color"
export CPCLI_PATH="$HOME/competitive_programming/cpcli/"

# MacOS
if [[ "$(uname)" == "Darwin" ]]; then
  export TERMINAL=iterm2
fi

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

if [ -f "$theme_autocompletion_file" ]; then
  source "$theme_autocompletion_file"
fi

if [ ! -d "/etc/nixos" ]; then
  # if archlinux then source conda env
  # >>> conda initialize >>>
  # !! Contents within this block are managed by 'conda init' !!
  __conda_setup="$('/home/cunbidun/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
      eval "$__conda_setup"
  else
      if [ -f "/home/cunbidun/miniconda3/etc/profile.d/conda.sh" ]; then
          . "/home/cunbidun/miniconda3/etc/profile.d/conda.sh"
      else
          export PATH="/home/cunbidun/miniconda3/bin:$PATH"
      fi
  fi
  unset __conda_setup
  # <<< conda initialize <<<
  
  export NVM_DIR="$HOME/.config/nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
fi

# Check if the current session is an SSH connection
if [ -n "$SSH_CONNECTION" ]; then
  if ! systemd-inhibit --list | grep "Active SSH session" > /dev/null; then
    systemd-inhibit --what=idle --who=me --why="Active SSH session" sleep infinity &
  fi
fi
