[meta]
version = 1
name = "Theme Manager Gruvbox Light"
description = "Gruvbox Material light hard theme"
variant = "light"
inherits = "vicinae-light"

[colors.accents]
blue = "#45707a"
green = "#6c782e"
magenta = "#945e80"
orange = "#c35e0a"
red = "#c14a4a"
yellow = "#b47109"
cyan = "#4c7a5d"
purple = "#945e80"

[colors.core]
accent = "colors.accents.yellow"
accent_foreground = "#fbf1c7"
background = "#fbf1c7"
foreground = "#3c3836"
secondary_background = "#f2e5bc"
border = "#d5c4a1"

[colors.main_window]
border = "colors.core.border"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "colors.core.border"

[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#7c6f64"
danger = "colors.accents.red"
success = "colors.accents.green"
placeholder = "#928374"
selection = { background = "colors.core.accent", foreground = "#fbf1c7" }

[colors.text.links]
default = "colors.accents.blue"
visited = "colors.accents.purple"

[colors.input]
border = "colors.core.border"
border_focus = "colors.core.accent"
border_error = "colors.accents.red"

[colors.button.primary]
background = "colors.core.secondary_background"
foreground = "colors.core.foreground"
hover = { background = "#ebdbb2" }
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "colors.core.foreground"
secondary_foreground = "#7c6f64"

[colors.list.item.selection]
background = "#ebdbb2"
foreground = "colors.core.foreground"
secondary_background = "colors.core.accent"
secondary_foreground = "#7c6f64"

[colors.grid.item]
background = "colors.core.secondary_background"
hover = { outline = "colors.core.accent" }
selection = { outline = "colors.core.accent" }

[colors.scrollbars]
background = "#d5c4a1"

[colors.loading]
bar = "colors.core.accent"
spinner = "colors.core.foreground"
