[meta]
version = 1
name = "Theme Manager Gruvbox Dark"
description = "Gruvbox Material dark hard theme"
variant = "dark"
inherits = "vicinae-dark"

[colors.accents]
blue = "#7daea3"
green = "#a9b665"
magenta = "#d3869b"
orange = "#e78a4e"
red = "#ea6962"
yellow = "#d8a657"
cyan = "#89b482"
purple = "#d3869b"

[colors.core]
accent = "colors.accents.yellow"
accent_foreground = "#1d2021"
background = "#1d2021"
foreground = "#ddc7a1"
secondary_background = "#282828"
border = "#3c3836"

[colors.main_window]
border = "colors.core.border"
footer = { background = "colors.core.secondary_background" }

[colors.settings_window]
border = "colors.core.border"

[colors.shortcut]
border = "colors.core.border"

[colors.text]
default = "colors.core.foreground"
muted = "#928374"
danger = "colors.accents.red"
success = "colors.accents.green"
placeholder = "#7c6f64"
selection = { background = "colors.core.accent", foreground = "#1d2021" }

[colors.text.links]
default = "colors.accents.blue"
visited = "colors.accents.purple"

[colors.input]
border = "colors.core.border"
border_focus = "colors.core.accent"
border_error = "colors.accents.red"

[colors.button.primary]
background = "colors.core.secondary_background"
foreground = "colors.core.foreground"
hover = { background = "#32302f" }
focus = { outline = "colors.core.accent" }

[colors.list.item.hover]
foreground = "colors.core.foreground"
secondary_foreground = "#928374"

[colors.list.item.selection]
background = "#3a3324"
foreground = "colors.core.foreground"
secondary_background = "colors.core.accent"
secondary_foreground = "#928374"

[colors.grid.item]
background = "colors.core.secondary_background"
hover = { outline = "colors.core.accent" }
selection = { outline = "colors.core.accent" }

[colors.scrollbars]
background = "#504945"

[colors.loading]
bar = "colors.core.accent"
spinner = "colors.core.foreground"
